name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      release_created: ${{ steps.release.outputs.release_created }}
      id: ${{ steps.release.outputs.id }}
      name: ${{ steps.release.outputs.name }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.release.outputs.sha }}
      body: ${{ steps.release.outputs.body }}
      html_url: ${{ steps.release.outputs.html_url }}
      draft: ${{ steps.release.outputs.draft }}
      upload_url: ${{ steps.release.outputs.upload_url }}
      path: ${{ steps.release.outputs.path }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      prs_created: ${{ steps.release.outputs.prs_created }}
    steps:
      # https://github.com/googleapis/release-please-action
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/googleapis/release-please-action?tab=readme-ov-file#github-credentials

      - name: Output Release Information
        run: |
          {
            echo "releases_created=${{ steps.release.outputs.releases_created }}"
            echo "release_created=${{ steps.release.outputs.release_created }}"
            echo "id=${{ steps.release.outputs.id }}"
            echo "name=${{ steps.release.outputs.name }}"
            echo "tag_name=${{ steps.release.outputs.tag_name }}"
            echo "sha=${{ steps.release.outputs.sha }}"
            echo "body<<EOF"
            echo "${{ steps.release.outputs.body }}"
            echo "EOF"
            echo "html_url=${{ steps.release.outputs.html_url }}"
            echo "draft=${{ steps.release.outputs.draft }}"
            echo "upload_url=${{ steps.release.outputs.upload_url }}"
            echo "path=${{ steps.release.outputs.path }}"
            echo "version=${{ steps.release.outputs.version }}"
            echo "major=${{ steps.release.outputs.major }}"
            echo "minor=${{ steps.release.outputs.minor }}"
            echo "patch=${{ steps.release.outputs.patch }}"
            echo "paths_released=${{ steps.release.outputs.paths_released }}"
            echo "prs_created=${{ steps.release.outputs.prs_created }}"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Print Release Details
        env:
          RELEASE: ${{ toJSON(steps.release.outputs) }}
        run: echo "$RELEASE"

  deploy-staging: # test with staging
    name: Staging
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      stage: staging
